import { MIAMI_SESSION_KEY, DEFAULT_CIRCUIT, SESSION_CIRCUIT_MAP } from '../../shared/constants.js';
import { fetchAllLocationData, fetchDrivers, fetchLaps, calculateBounds } from '../../shared/api.js';
import * as playback from '../../shared/playback.js';
import * as driverData from '../../shared/drivers.js';
import { SceneManager } from './scene.js';
import { CircuitLoader } from './circuit.js';
import { DriverDotManager } from './drivers.js';
import { PostProcessing } from './postfx.js';

async function main(){const params=new URLSearchParams(window.location.search);const speed=parseFloat(params.get('speed')??'1.0');const startLap=params.has('start')?parseInt(params.get('start'),10):null;const devMode=params.has('dev');const circuit=params.get('circuit')??SESSION_CIRCUIT_MAP[MIAMI_SESSION_KEY]??DEFAULT_CIRCUIT;const [locationRecords,driversArray,lapsData]=await Promise.all([fetchAllLocationData(MIAMI_SESSION_KEY),fetchDrivers(MIAMI_SESSION_KEY),fetchLaps(MIAMI_SESSION_KEY)]);const openF1Bounds=calculateBounds(locationRecords);const recordsByDriver={};for(const r of locationRecords){const k=String(r.driver_number);(recordsByDriver[k]??=[]).push(r);}const driverPlaybackIndex=Object.fromEntries(Object.keys(recordsByDriver).map((k)=>[k,0]));let startOffsetMs=0;if(startLap!==null){const lapEntries=lapsData.filter((l)=>l.lap_number===startLap&&l.date_start);if(lapEntries.length>0){const lapStartEpoch=Math.min(...lapEntries.map((l)=>new Date(l.date_start).getTime()));startOffsetMs=lapStartEpoch-new Date(locationRecords[0].date).getTime();}}
playback.init(locationRecords,{speed,startOffsetMs});driverData.init(driversArray);const scene=new SceneManager(document.getElementById('three-canvas'));const {spline,modelBounds}=await CircuitLoader.load(circuit,scene.scene);scene.positionCamera(modelBounds);const dots=new DriverDotManager(scene.scene,document.getElementById('css2d-layer'),scene.camera,scene.renderer,spline,driverData.getAllDrivers());const postfx=new PostProcessing(scene.renderer,scene.scene,scene.camera);let devPanel=null;if(devMode){const {DevPanel}=await import('./dev-panel.js');devPanel=new DevPanel({onSpeedChange:(v)=>playback.setSpeed(v)});devPanel.mount();}
requestAnimationFrame(function tick(){const sessionTime=playback.getCurrentSessionTime();for(const [n,records] of Object.entries(recordsByDriver)){let idx=driverPlaybackIndex[n];while(idx+1<records.length&&new Date(records[idx+1].date).getTime()<=sessionTime)idx++;driverPlaybackIndex[n]=idx;dots.updateTarget(n,records[idx],openF1Bounds,modelBounds)}dots.lerpAll();postfx.render();devPanel?.tick(sessionTime,0);requestAnimationFrame(tick);});}
main().catch((err)=>{console.error('[track-map] Startup failed:',err);const pre=document.createElement('pre');pre.style.color='red';pre.style.padding='20px';pre.textContent=String(err?.stack||err);document.body.appendChild(pre);});
